version: '3.9'
services:
  db:
   image: mysql
   volumes:
      - "dbdata:/var/lib/mysql"
   container_name: db
   environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=sistfin
      - MYSQL_USER=user_sistfin
      - MYSQL_PASSWORD=sistfin@123
   healthcheck:
    test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
    start_period: 60s
   ports:
      - 3306:3306
   networks: 
     - cantina-network  
  web:
    build: .
    container_name: sistfin-api
    restart: on-failure    
    ports:
      - 8080:8080
    environment: 
      - DATABASE_HOST=db  
      - DATABASE_USER=user_sistfin
      - DATABASE_NAME=sistfin
      - DATABASE_PORT=3306
    networks: 
      - cantina-network  
    depends_on:
     db:
      condition: service_healthy   
networks: 
  cantina-network:
    driver: bridge
volumes:
   dbdata:    